import { CourseRoadmapSeed } from './types';

export const algorithmsRoadmap: CourseRoadmapSeed = {
  courseId: 'algorithms',
  modules: [
    {
        "title": "Module 0 — Algorithm Foundations",
        "description": "Core foundations: Algorithms vs Programs, pseudocode, dry running, program state, edge cases, Big-O, Big-Omega, Big-Theta, and complexities from O(1) to O(n!).",
        "icon": "brain",
        "topics": [
            "What is an Algorithm?",
            "Algorithm vs Program",
            "Algorithm vs Data Structure",
            "Input → Process → Output",
            "How Algorithms Work",
            "Step-by-Step Algorithm Representation",
            "Pseudocode",
            "Flowcharts",
            "Dry Run",
            "Tracing an Algorithm",
            "State of a Program",
            "Variables During Execution",
            "Algorithm Correctness",
            "Edge Cases",
            "Base Cases",
            "Algorithm Efficiency",
            "Time Complexity Introduction",
            "Space Complexity Introduction",
            "Best Case",
            "Average Case",
            "Worst Case",
            "Big-O",
            "Big-Ω",
            "Big-Θ",
            "O(1)",
            "O(log n)",
            "O(n)",
            "O(n log n)",
            "O(n²)",
            "O(n³)",
            "O(2ⁿ)",
            "O(n!)",
            "Comparing Complexities",
            "Time-Space Tradeoff"
        ]
    },
    {
        "title": "Module 1 — Level 1: Little Coder (Basic Problem Solving)",
        "description": "Essential problem-solving building blocks: counting, sum, min/max, duplicates, occurrences, swapping, palindrome checks, digit extraction, primes, factorial, and GCD.",
        "icon": "code-braces",
        "topics": [
            "Counting Algorithm",
            "Summation Algorithm",
            "Minimum and Maximum",
            "Average Calculation",
            "Frequency Counting",
            "Duplicate Detection",
            "Searching for an Element",
            "Counting Occurrences",
            "Finding First Occurrence",
            "Finding Last Occurrence",
            "Finding Unique Element",
            "Finding Missing Element",
            "Finding Repeated Element",
            "Swapping Elements",
            "Reversing Data",
            "Checking Palindrome",
            "Digit Extraction",
            "Number Reversal",
            "Digit Counting",
            "Sum of Digits",
            "Product of Digits",
            "Even/Odd Algorithms",
            "Prime Checking",
            "Prime Number Generation",
            "Factorial",
            "Fibonacci",
            "GCD",
            "LCM",
            "Power Calculation",
            "Fast Power"
        ]
    },
    {
        "title": "Module 2 — Level 1: Mathematical Algorithms",
        "description": "Number theory and math algorithms: divisibility, Sieve of Eratosthenes, Euclidean GCD, modular arithmetic, Fermat's Little Theorem, Pascal's Triangle, and matrix exponentiation.",
        "icon": "calculator-variant",
        "topics": [
            "Divisibility",
            "Factors of a Number",
            "Prime Numbers",
            "Sieve of Eratosthenes",
            "Segmented Sieve",
            "GCD — Euclidean Algorithm",
            "Extended Euclidean Algorithm",
            "LCM",
            "Modular Arithmetic",
            "Modular Addition",
            "Modular Multiplication",
            "Modular Exponentiation",
            "Fast Exponentiation",
            "Fermat's Little Theorem",
            "Euler's Totient",
            "Modular Inverse",
            "Combinations",
            "Permutations",
            "Pascal's Triangle",
            "Binomial Coefficients",
            "Matrix Addition",
            "Matrix Multiplication",
            "Matrix Exponentiation",
            "Fast Doubling Fibonacci",
            "Bitwise Mathematics",
            "Number Theory Basics"
        ]
    },
    {
        "title": "Module 3 — Level 2: Beginner (Searching Algorithms)",
        "description": "Comprehensive search algorithms: Linear Search, Sentinel, Binary Search, First/Last Occurrence, Bounds, Rotated Array, Peak Element, and Binary Search on Answer.",
        "icon": "magnify",
        "topics": [
            "What is Searching?",
            "Linear Search",
            "Sentinel Linear Search",
            "Binary Search",
            "Binary Search on Sorted Array",
            "Binary Search First Occurrence",
            "Binary Search Last Occurrence",
            "Lower Bound",
            "Upper Bound",
            "Floor and Ceiling",
            "Search Insert Position",
            "Count Occurrences Using Binary Search",
            "Search in Rotated Sorted Array",
            "Search in Rotated Array with Duplicates",
            "Find Minimum in Rotated Array",
            "Peak Element",
            "Bitonic Array Search",
            "Infinite Sorted Array Search",
            "Exponential Search",
            "Jump Search",
            "Interpolation Search",
            "Ternary Search",
            "Fibonacci Search",
            "Binary Search on Answer",
            "Parametric Search",
            "Search on Monotonic Functions"
        ]
    },
    {
        "title": "Module 4 — Level 2: Beginner (Sorting Algorithms)",
        "description": "Mastering comparison and non-comparison sorting: Bubble, Selection, Insertion, Merge Sort, Quick Sort, Heap Sort, Counting, Radix, Bucket, and Tim Sort with stability analysis.",
        "icon": "sort-ascending",
        "topics": [
            "Sorting Fundamentals",
            "Bubble Sort",
            "Selection Sort",
            "Insertion Sort",
            "Merge Sort",
            "Quick Sort & Partition Schemes",
            "Heap Sort",
            "Counting Sort",
            "Radix Sort",
            "Bucket Sort",
            "Shell Sort",
            "Tim Sort",
            "Stability & In-place Sorting",
            "Sorting Complexity Comparison & Optimization"
        ]
    },
    {
        "title": "Module 5 — Level 3: Problem Solver (Two Pointers & Sliding Window)",
        "description": "Core interview array techniques: Opposite & same direction two pointers, fixed and variable sliding windows, 1D/2D prefix sums, difference arrays, and coordinate compression.",
        "icon": "arrow-left-right",
        "topics": [
            "Two Pointer Basics",
            "Opposite Direction Pointers",
            "Same Direction Pointers",
            "Fast and Slow Pointer Technique",
            "Sliding Window Fixed Size",
            "Sliding Window Dynamic Size",
            "Longest Substring Window",
            "Minimum Window Substring",
            "Prefix Sum 1D & 2D",
            "Difference Array Technique",
            "Subarray Sums & Invariants",
            "Coordinate Compression"
        ]
    },
    {
        "title": "Module 6 — Level 4: Recursive Thinker (Hashing & Backtracking)",
        "description": "Deep recursion, state exploration, permutations, combinations, and backtracking pruning: N-Queens, Sudoku Solver, Word Search, and Subset Sum.",
        "icon": "source-branch",
        "topics": [
            "Hash Maps & Frequency Counting",
            "Hash Sets & Uniqueness",
            "Recursion Foundations & Call Stack",
            "Recursion Tree & State Visualization",
            "Generating Subsets & Power Set",
            "Generating Permutations & Combinations",
            "Backtracking: Choose → Explore → Undo",
            "Backtracking: N-Queens Problem",
            "Backtracking: Sudoku Solver",
            "Backtracking: Word Search",
            "Backtracking: Subset Sum & Partition"
        ]
    },
    {
        "title": "Module 7 — Level 5: Greedy Thinker (Greedy & Divide-and-Conquer)",
        "description": "Optimal subproblems and greedy choice property: Activity Selection, Fractional Knapsack, Huffman Coding, Jump Game, Closest Pair, and Strassen's Multiplication.",
        "icon": "lightning-bolt",
        "topics": [
            "Greedy Choice Property & Invariants",
            "Activity Selection & Interval Scheduling",
            "Fractional Knapsack Problem",
            "Huffman Coding & Optimal Prefix Codes",
            "Jump Game & Greedy Optimization",
            "Divide and Conquer Principles",
            "Binary Exponentiation via Divide & Conquer",
            "Closest Pair of Points O(n log n)",
            "Strassen's Matrix Multiplication"
        ]
    },
    {
        "title": "Module 8 — Level 6: DP Thinker (Dynamic Programming)",
        "description": "From recursion to DP: Memoization, Tabulation, 1D DP, 0/1 Knapsack, LCS, LIS in O(n log n), Matrix Chain, Bitmask DP, Digit DP, Tree DP, Graph DP, and Convex Hull Trick.",
        "icon": "table-cog",
        "topics": [
            "DP Foundations: Overlapping Subproblems & Optimal Substructure",
            "Memoization vs Tabulation (Top-Down vs Bottom-Up)",
            "1D DP: Climbing Stairs & House Robber",
            "Coin Change & Unbounded Knapsack",
            "0/1 Knapsack Problem",
            "Longest Common Subsequence (LCS)",
            "Longest Increasing Subsequence (LIS) in O(n log n)",
            "Matrix Chain Multiplication & Interval DP",
            "Bitmask DP: Traveling Salesperson Problem",
            "Digit DP: Counting Numbers with Constraints",
            "Tree DP: Tree Diameter & Subtree Aggregations",
            "Graph DP: Shortest Paths with at most K Edges",
            "Convex Hull Trick & Knuth Optimization"
        ]
    },
    {
        "title": "Module 9 — Level 7: Graph Explorer (Graph Algorithms & Network Flow)",
        "description": "Graph traversals, MST, shortest paths, connectivity, and network flow: BFS, DFS, Topological Sort, DSU, Kruskal, Prim, Dijkstra, Bellman-Ford, Floyd-Warshall, Kosaraju, Tarjan, Dinic.",
        "icon": "graph-outline",
        "topics": [
            "Graph Representations: Adjacency List & Matrix",
            "Breadth-First Search (BFS) & Shortest Path in Unweighted Graph",
            "Depth-First Search (DFS) & Cycle Detection",
            "Topological Sort: Kahn's Algorithm & DFS",
            "Disjoint Set Union (DSU / Union-Find) with Rank & Path Compression",
            "Minimum Spanning Tree: Kruskal's Algorithm",
            "Minimum Spanning Tree: Prim's Algorithm",
            "Single-Source Shortest Path: Dijkstra's Algorithm",
            "Single-Source Shortest Path: Bellman-Ford & Negative Cycles",
            "All-Pairs Shortest Path: Floyd-Warshall",
            "Strongly Connected Components (SCC): Kosaraju's Algorithm",
            "Strongly Connected Components (SCC): Tarjan's Algorithm",
            "Bridges & Articulation Points in Graphs",
            "Eulerian Path and Circuit (Hierholzer's Algorithm)",
            "Hamiltonian Path and NP-Completeness",
            "Bipartite Graph Checking & Maximum Matching",
            "Hopcroft-Karp Maximum Bipartite Matching",
            "Network Flow: Ford-Fulkerson & Residual Networks",
            "Network Flow: Edmonds-Karp Algorithm",
            "Network Flow: Dinic's Algorithm",
            "Min-Cut Max-Flow Theorem",
            "Min-Cost Max-Flow Foundations"
        ]
    },
    {
        "title": "Module 10 — Level 8: Advanced Data Structures & String Algorithms",
        "description": "High-performance structures & strings: Segment Tree with Lazy Propagation, Fenwick Tree, Sparse Table, Treap, Trie, KMP, Z-Algorithm, Suffix Array & LCP, Suffix Tree, Aho-Corasick, Manacher, CRT.",
        "icon": "file-tree-outline",
        "topics": [
            "Segment Tree: Construction & Point Update",
            "Segment Tree: Range Query & Lazy Propagation",
            "Fenwick Tree (Binary Indexed Tree / BIT)",
            "Sparse Table & Range Minimum Query (RMQ)",
            "Treap & Splay Tree Foundations",
            "Trie: Prefix Tree & Autocomplete",
            "String Hashing & Rabin-Karp Algorithm",
            "KMP Algorithm (Knuth-Morris-Pratt)",
            "Z-Algorithm for Pattern Matching",
            "Suffix Array & Longest Common Prefix (LCP)",
            "Suffix Tree Architecture",
            "Aho-Corasick Multi-Pattern Matching",
            "Manacher's Algorithm for Longest Palindromic Substring",
            "Chinese Remainder Theorem (CRT)",
            "Mobius Inversion & Number Theory Functions",
            "Computational Geometry: Convex Hull (Graham Scan)",
            "Sweep Line Algorithm: Line Segment Intersection",
            "Randomized Algorithms & Reservoir Sampling"
        ]
    },
    {
        "title": "Module 11 — Algorithm Patterns Library",
        "description": "Pattern recognition master catalog: Clues, trigger conditions, standard templates, and complexity profiles across 15 core algorithm patterns.",
        "icon": "shape-outline",
        "topics": [
            "Pattern: Brute Force & State Enumeration",
            "Pattern: Frequency Counting & Hash Maps",
            "Pattern: Two Pointers (Opposite & Fast/Slow)",
            "Pattern: Sliding Window (Fixed & Variable)",
            "Pattern: Prefix Sum & Difference Array",
            "Pattern: Binary Search & Binary Search on Answer",
            "Pattern: Monotonic Stack & Monotonic Queue",
            "Pattern: Top K Elements & K-Way Merge",
            "Pattern: Backtracking (Choose → Explore → Undo)",
            "Pattern: Dynamic Programming Transitions",
            "Pattern: Breadth-First Search & Multi-Source BFS",
            "Pattern: Depth-First Search & Connected Components",
            "Pattern: Union-Find & Disjoint Sets",
            "Pattern: Greedy & Exchange Arguments",
            "Pattern: Sweep Line & Coordinate Compression"
        ]
    },
    {
        "title": "Module 12 — Advanced Problem-Solving Patterns & Proof",
        "description": "Mathematical rigor: Mathematical induction, loop invariants, proof by contradiction, exchange arguments, Master Theorem, and amortized potential method.",
        "icon": "shield-check-outline",
        "topics": [
            "Choose → Explore → Undo Invariant",
            "Reduce Search Space & Invariant-Based Thinking",
            "Sort Then Solve & Hash Then Solve",
            "Transform & Reverse the Problem (Working Backwards)",
            "Exchange Arguments in Greedy Proofs",
            "Mathematical Induction & Loop Invariants",
            "Proof by Contradiction in Algorithms",
            "Master Theorem & Recurrence Relations",
            "Amortized Analysis: Aggregate, Accounting & Potential Method",
            "Complexity Lower Bounds & Trade-offs (Time vs Space)"
        ]
    },
    {
        "title": "Module 13 — Level 9: Competitive Programmer (Optimization & Fast I/O)",
        "description": "Contest-ready performance: Fast I/O, bitwise arithmetic tricks, Mo's Algorithm for offline range queries, meet-in-the-middle, and randomized collision reduction.",
        "icon": "trophy-outline",
        "topics": [
            "Fast I/O & Constant Factor Optimization",
            "Bitwise Manipulation Tricks & Bitmasks",
            "Offline Queries & Mo's Algorithm",
            "Meet-in-the-Middle Strategy",
            "Interactive Problems & Hidden Invariants",
            "Randomized Approaches & Hash Collisions",
            "Amortized Techniques in Contests"
        ]
    },
    {
        "title": "Module 14 — Level 10: Algorithm Master (Visual Debugging & Tracing Lab)",
        "description": "Deep systematic debugging: Reading code line by line, dry run tables, variable & memory state tracking, recursion call tree inspection, and DP table tracing.",
        "icon": "bug-outline",
        "topics": [
            "Reading Code Line by Line & Dry Run",
            "Variable State & Memory Tracking",
            "Recursion Stack & Call Tree Tracing",
            "DP Table & Transition Matrix Tracking",
            "Finding Off-by-One Errors & Infinite Loops",
            "Integer Overflow & Edge Case Verification",
            "Debugging Brute Force vs Optimized Implementations"
        ]
    }
]
};
