import { CourseRoadmapSeed } from './types';

export const aptitudeRoadmap: CourseRoadmapSeed = {
  courseId: 'aptitude',
  modules: [
    // --- STAGE 1: BEGINNER & NUMBER FUNDAMENTALS ---
    {
      title: 'Number System & Properties',
      description: 'Classification of numbers, prime factorization, factors, and divisibility properties.',
      icon: 'calculator-outline',
      topics: [
        'Types of Numbers: Natural, Whole, Integers, Rational, and Irrational',
        'Prime Numbers, Co-Primes, and Prime Factorization Method',
        'Finding Number of Factors, Sum of Factors, and Even/Odd Factors',
        'Divisibility Rules for 2, 3, 4, 5, 6, 8, 9, 10, and 11',
        'Advanced Divisibility Rules for 7, 13, 17, 19, and Combined Divisibility',
        'Power Cycle and Cyclicity of Numbers',
        'Finding Unit Digit of Expressions and Large Exponents',
        'Finding the Last Two Digits of Numerical Expressions',
      ],
    },
    {
      title: 'HCF and LCM',
      description: 'Highest common factor, least common multiple, and application word problems.',
      icon: 'git-merge-outline',
      topics: [
        'HCF Fundamentals: Prime Factorization and Long Division Method',
        'LCM Fundamentals: Division Method and Factor Method',
        'HCF and LCM of Fractions and Decimals',
        'Product of Two Numbers = HCF × LCM Relationship',
        'Word Problems on Largest Common Measures and Containers',
        'Word Problems on Bell Rings, Traffic Lights, and Circular Track Lap Meets',
      ],
    },
    {
      title: 'Remainders & Modulo Arithmetic',
      description: 'Remainder theorem, negative remainders, Euler totient, and power remainders.',
      icon: 'infinite-outline',
      topics: [
        'Basic Remainder Concepts and Division Algorithm (Dividend = Divisor × Q + R)',
        'Negative Remainder Concept and Calculation Shortcuts',
        'Successive Division and Finding Original Numbers from Remainders',
        'Fermat Little Theorem Applications in Exponent Remainders',
        "Euler's Totient Function (phi) and Power Remainders",
        'Wilson Theorem and Remainder of Factorials',
      ],
    },
    {
      title: 'Fractions and Decimals',
      description: 'Operations, comparison techniques, recurring decimals, and approximations.',
      icon: 'pie-chart-outline',
      topics: [
        'Types of Fractions: Proper, Improper, Mixed, and Equivalent',
        'Comparison of Fractions: Cross-Multiplication, LCM, and Decimal Methods',
        'Recurring and Non-Recurring Decimals: Converting to Vulgar Fractions',
        'Decimal Operations, Rounding Rules, and Precision Calculations',
        'Ascending and Descending Order of Complex Fractions',
      ],
    },
    {
      title: 'Simplification and BODMAS',
      description: 'Order of operations, algebraic identities, surds, and indices simplification.',
      icon: 'sparkles-outline',
      topics: [
        'VBODMAS Rule: Vinculum, Brackets, Order, Division, Multiplication, Addition, Subtraction',
        'Algebraic Simplification Identities ((a+b)², (a-b)², (a³+b³), (a³-b³))',
        'Laws of Indices and Powers in Equations',
        'Surds Rationalization and Comparison of Radical Values',
        'Square Roots and Cube Roots Extraction Shortcuts',
        'Approximation Techniques for Fast Mental Math',
      ],
    },

    // --- STAGE 2: FUNDAMENTALS OF RATIO & PERCENTAGES ---
    {
      title: 'Ratio and Proportion',
      description: 'Direct and inverse variation, compound ratio, and proportion theorems.',
      icon: 'swap-horizontal-outline',
      topics: [
        'Ratio Fundamentals, Simplification, and Lowest Terms',
        'Continuous Ratio: Combining A:B and B:C into A:B:C and A:B:C:D',
        'Mean Proportional, Third Proportional, and Fourth Proportional',
        'Duplicate, Triplicate, Sub-duplicate, and Sub-triplicate Ratios',
        'Componendo and Dividendo Theorem Applications',
        'Direct and Inverse Proportion Variation Word Problems',
        'Dividing Given Quantities in Multi-Part Ratios',
      ],
    },
    {
      title: 'Percentages',
      description: 'Fraction equivalence chart, percentage change, and consumption problems.',
      icon: 'trending-up-outline',
      topics: [
        'Fraction to Percentage Equivalence Chart (1/2 to 1/25)',
        'Percentage Increase and Decrease Fundamentals',
        'Successive Percentage Change Formula: (A + B + AB/100)',
        'Price, Consumption, and Expenditure Balance Problems',
        'Population Growth and Multi-Year Depreciation Calculations',
        'Exam Passing Marks, Maximum Marks, and Percentage Score Scenarios',
        'Election Voting, Valid Votes, and Majority Margin Problems',
      ],
    },
    {
      title: 'Average',
      description: 'Arithmetic mean, weighted average, inclusion/exclusion, and age updates.',
      icon: 'analytics-outline',
      topics: [
        'Arithmetic Mean Concept and Direct Calculation Formula',
        'Weighted Average Formula: (n1A1 + n2A2) / (n1 + n2)',
        'Change in Average When Values are Added, Removed, or Replaced',
        'Correcting Errors: Calculating True Average with Misread Data',
        'Batting and Bowling Average Problems in Cricket',
        'Consecutive Numbers and Symmetric Sets Average Properties',
      ],
    },
    {
      title: 'Profit, Loss and Discount',
      description: 'CP, SP, MP, markup, single/successive discount, and dishonest merchant tricks.',
      icon: 'cash-outline',
      topics: [
        'Cost Price (CP), Selling Price (SP), Profit%, and Loss% Formulas',
        'Finding CP and SP When Profit% or Loss% is Known',
        'Marked Price (MP), Markup Percentage, and Discount Percentage',
        'Successive Discounts and Single Equivalent Discount Formula',
        'Promotional Offers: Buy X Get Y Free Discount Calculations',
        'Dishonest Seller Problems: Faulty Weights and Cheating in Purchase/Sale',
        'Equal Selling Price Scenarios: Profit on One and Loss on Another',
      ],
    },
    {
      title: 'Simple Interest',
      description: 'Principal, rate, tenure, multi-year growth, and installment repayment.',
      icon: 'wallet-outline',
      topics: [
        'Simple Interest Core Formula: SI = (P × R × T) / 100',
        'Calculating Principal, Rate of Interest, and Time Duration',
        'Sum Doubles, Triples, or Multiplies in N Years Principle',
        'Different Rates of Interest for Different Time Intervals',
        'Equal Amount Earned from Multiple Investments',
        'Simple Interest Debt Installments and Repayment Formulas',
      ],
    },
    {
      title: 'Compound Interest',
      description: 'Annual, half-yearly, and quarterly compounding, and CI-SI difference.',
      icon: 'stats-chart-outline',
      topics: [
        'Compound Interest Core Formula: A = P(1 + R/100)^n',
        'Compounding Half-Yearly (Semi-Annually) and Quarterly Variations',
        'Difference Between CI and SI for 2 Years: P(R/100)²',
        'Difference Between CI and SI for 3 Years: P(R/100)² × (3 + R/100)',
        'Equal Annual Installments in Compound Interest Loans',
        'Compound Interest Growth at Varying Annual Rates',
      ],
    },

    // --- STAGE 3: INTERMEDIATE ARITHMETIC & WORK/MOTION ---
    {
      title: 'Time and Work',
      description: 'Unit efficiency, LCM method, alternate work days, and wage distribution.',
      icon: 'construct-outline',
      topics: [
        'Work, Time, and Individual Efficiency Relationships',
        'LCM Method for Multi-Person Work Completion',
        'Workers Leaving Before Completion or Joining Mid-Way',
        'Alternate Days Work Schedules and Remaining Work Cycles',
        'Men, Women, and Children Work Equivalence Equations',
        'Distribution of Wages and Earnings Proportional to Work Done',
      ],
    },
    {
      title: 'Pipes and Cisterns',
      description: 'Inlet pipes, outlet leaks, alternate filling, and capacity determination.',
      icon: 'water-outline',
      topics: [
        'Inlet Pipe Filling Rates and Tank Capacity Fundamentals',
        'Outlet Pipes and Bottom Leaks as Negative Work',
        'Multiple Inlets and Outlets Operating Simultaneously',
        'Alternating Filling and Emptying Pipe Operations',
        'Determining Tank Volume from Cross-Sectional Flow Rates',
        'Pipes Turned Off Before Tank Fills Calculations',
      ],
    },
    {
      title: 'Time, Speed and Distance',
      description: 'Speed relationships, unit conversion, average speed, and relative speed.',
      icon: 'speedometer-outline',
      topics: [
        'Speed, Distance, and Time Core Formulas: S = D / T',
        'Unit Conversion: km/h to m/s (5/18 factor) and vice versa',
        'Average Speed for Equal Distances (2xy / (x+y)) and Unequal Distances',
        'Early and Late Arrival Scenarios and Distance Calculation',
        'Stoppage Time and Average Speed Without Stoppages',
        'Circular Track Motion: Same Direction and Opposite Direction Meets',
      ],
    },
    {
      title: 'Problems on Trains',
      description: 'Trains crossing poles, platforms, tunnels, and relative speed collisions.',
      icon: 'train-outline',
      topics: [
        'Train Crossing a Stationary Point, Pole, or Person (Length = Distance)',
        'Train Crossing a Stationary Platform, Bridge, or Tunnel',
        'Two Trains Moving in Opposite Directions: Relative Speed Sum',
        'Two Trains Moving in Same Direction: Relative Speed Difference',
        'Two Trains Starting from Opposite Stations and Crossing Point Time',
        'Train Crossing a Moving Person or Vehicle',
      ],
    },
    {
      title: 'Boats and Streams',
      description: 'Still water speed, current speed, downstream, upstream, and round trips.',
      icon: 'boat-outline',
      topics: [
        'Speed in Still Water (u) and Stream Current Speed (v)',
        'Downstream Speed (u + v) and Upstream Speed (u - v)',
        'Calculating Still Water Speed: (Downstream + Upstream) / 2',
        'Calculating Stream Speed: (Downstream - Upstream) / 2',
        'Round Trip Average Speed and Total Journey Time Equations',
        'Time Taken Upstream is N Times Downstream Distance Problems',
      ],
    },
    {
      title: 'Mixtures and Alligation',
      description: 'Alligation cross rule, mean price, and repeated dilution formulas.',
      icon: 'flask-outline',
      topics: [
        'Rule of Alligation Framework and Cross Method Concept',
        'Determining the Ratio of Mixing Ingredients of Different Costs',
        'Finding Mean Price and Weighted Value of Mixtures',
        'Repeated Dilution Formula: Final = Initial × (1 - x/V)^n',
        'Mixing Solutions of Different Acid/Water Concentrations',
        'Mixing Three or More Ingredients of Different Values',
      ],
    },
    {
      title: 'Partnership',
      description: 'Simple and compound partnerships, sleeping partners, and profit ratios.',
      icon: 'people-outline',
      topics: [
        'Simple Partnership: Profit Sharing When Time is Constant (P1:P2 = C1:C2)',
        'Compound Partnership: Unequal Capital and Unequal Time (P = Capital × Time)',
        'Working Partners Receiving Salary/Bonus Before Profit Split',
        'Sleeping Partners vs Active Operating Partners',
        'Changes in Capital: Partners Withdrawing or Adding Capital Mid-Year',
        'Pasture Grazing and Equipment Rent Sharing Problems',
      ],
    },
    {
      title: 'Problems on Ages',
      description: 'Present, past, and future age ratios, and linear equation systems.',
      icon: 'hourglass-outline',
      topics: [
        'Age Relationships: Present Age, Ago (Past), and Hence (Future)',
        'Setting Up Linear Equations from Age Ratio Conditions',
        'Constant Difference Principle: Difference Between Two Ages Never Changes',
        'Age Problems Involving Three or More Family Members',
        'Average Age of a Family Over Time Involving Births and Deaths',
      ],
    },

    // --- STAGE 4: ADVANCED TOPICS, ALGEBRA & COMBINATORICS ---
    {
      title: 'Permutations',
      description: 'Fundamental counting principle, linear and circular arrangements.',
      icon: 'shuffle-outline',
      topics: [
        'Fundamental Counting Principle (Multiplication and Addition Rules)',
        'Factorial Notation and Permutation Formula: nPr = n! / (n-r)!',
        'Permutations of Words with Repeated Letters (n! / p!q!r!)',
        'Arrangements Where Certain Letters Must Always Stay Together',
        'Arrangements Where Certain Letters Must Never Be Together',
        'Circular Permutations Formula: (n-1)! and Beaded Necklaces ((n-1)! / 2)',
      ],
    },
    {
      title: 'Combinations',
      description: 'Selection formulas, committee formation, and geometric points.',
      icon: 'grid-outline',
      topics: [
        'Selection Formula: nCr = n! / (r! × (n-r)!)',
        'Differences Between Permutation (Order Matters) and Combination (Selection)',
        'Forming Committees with Minimum/Maximum Gender and Role Constraints',
        'Geometry Problems: Lines and Triangles Formed from N Points',
        'Diagonals of a Polygon Formula: n(n-3) / 2',
        'Handshakes and Tournament Round-Robin Match Formulas',
      ],
    },
    {
      title: 'Probability',
      description: 'Sample space, coin, dice, card draws, and conditional probability.',
      icon: 'dice-outline',
      topics: [
        'Sample Space, Favorable Outcomes, and Classical Probability Definition',
        'Coin Toss Probability: Single, Double, Triple, and N Coins',
        'Dice Roll Probability: Single Die, Pair of Dice, and Sum Distribution',
        'Playing Cards Experiments: 52 Cards Distribution and Draws',
        'Colored Balls in Bags / Urns: With Replacement vs Without Replacement',
        'Independent Events and Multiplication Rule: P(A ∩ B) = P(A) × P(B)',
        'Mutually Exclusive Events and Addition Rule: P(A ∪ B) = P(A) + P(B)',
      ],
    },
    {
      title: 'Data Interpretation: Tables & Bar Charts',
      description: 'Tabular analysis, single/grouped bar charts, and percentage ratios.',
      icon: 'bar-chart-outline',
      topics: [
        'Tabular DI: Rapid Row and Column Sums, Averages, and Ratios',
        'Calculating Growth Rates and Year-over-Year Percentage Changes',
        'Single and Double Bar Charts: Comparing Category Values',
        'Stacked and Percentage Bar Charts Interpretation',
        'Estimating Calculations from High-Volume Data Tables',
      ],
    },
    {
      title: 'Data Interpretation: Line & Pie Charts',
      description: 'Trend analysis, degree to percentage conversion, and caselet DI.',
      icon: 'pie-chart-outline',
      topics: [
        'Line Graphs: Trend Identification, Fluctuations, and Peaks',
        'Pie Charts: Percentage Slices to Absolute Numerical Quantities',
        'Pie Charts: Converting Degree Slices (360°) to Percentages (100%)',
        'Dual Pie Charts: Cost Distribution vs Revenue Distribution Comparison',
        'Caselet DI: Converting Complex Paragraph Text into Data Tables',
        'Radar / Spider Web and Mixed Graph Combinations',
      ],
    },
    {
      title: 'Algebra Fundamentals',
      description: 'Linear equations, quadratic roots, inequalities, and extrema.',
      icon: 'code-slash-outline',
      topics: [
        'Linear Equations in One and Two Variables: Elimination & Substitution',
        'Quadratic Equations: Finding Roots Using Factorization and Quadratic Formula',
        'Sum and Product of Roots: α + β = -b/a and αβ = c/a',
        'Nature of Roots Determined by Discriminant (b² - 4ac)',
        'Polynomial Expressions and Remainder-Factor Theorem',
        'Linear Inequalities and Interval Notation on Number Line',
        'Finding Maximum and Minimum Values of Quadratic Functions',
      ],
    },
    {
      title: 'Geometry',
      description: 'Lines, angles, triangles, circles, chords, and polygons.',
      icon: 'shapes-outline',
      topics: [
        'Lines, Angles, Transversals, and Parallel Line Angle Pairs',
        'Triangles: Angle Sum Property, Exterior Angle Theorem, and Types',
        'Congruency and Similarity Criteria in Triangles',
        'Pythagoras Theorem and Pythagorean Triplets Applications',
        'Circles: Chords, Tangents, Secants, and Cyclic Quadrilaterals',
        'Polygons: Interior and Exterior Angles Formulas of Regular Polygons',
      ],
    },
    {
      title: 'Mensuration: 2D & 3D',
      description: 'Perimeter, area, volume, and surface area of planar and solid shapes.',
      icon: 'cube-outline',
      topics: [
        '2D Perimeter and Area: Triangles (Heron formula), Rectangles, Squares',
        '2D Area of Parallelograms, Trapeziums, Rhombus, and Circles',
        '3D Solids: Surface Area and Volume of Cube, Cuboid, and Cylinder',
        '3D Solids: Surface Area and Volume of Cone, Frustum, and Sphere',
        'Melting and Recasting: Conservation of Volume in Solid Reshaping',
        'Volume and Capacity of Tanks, Hollow Cylinders, and Spherical Shells',
      ],
    },
    {
      title: 'Clocks and Calendars',
      description: 'Hand angles, gaining/losing clocks, odd days, and leap years.',
      icon: 'time-outline',
      topics: [
        'Clock Hands Speed: Minute Hand (6°/min) vs Hour Hand (0.5°/min)',
        'Angle Between Clock Hands Formula: |30H - (11/2)M|',
        'Coinciding (0°), Opposite (180°), and Right Angles (90°) Frequency',
        'Faulty Clocks Gaining or Losing Time Calculations',
        'Calendar Odd Days Concept and Leap Year Counting Rules',
        'Determining the Day of the Week for Any Historical Date',
        'Repetition of Calendars and Same Month Calendar Rules',
      ],
    },
    {
      title: 'Data Sufficiency & Comparison',
      description: 'Evaluating sufficiency of premises and quantitative comparisons.',
      icon: 'help-circle-outline',
      topics: [
        'Two-Statement Data Sufficiency: Statement (1) vs (2) Evaluation',
        'Determining Unique Numerical Solutions vs Infinite Possibilities',
        'Avoiding Common Traps in Data Sufficiency Questions',
        'Quantitative Comparison: Evaluating Quantity A vs Quantity B',
        'Handling Variables with Unknown Signs (+, -, 0) in Inequalities',
        'Eliminating Unnecessary Lengthy Calculations Using Shortcuts',
      ],
    },
    {
      title: 'Advanced Quantitative Aptitude',
      description: 'Higher polynomials, progressions (AP/GP/HP), and coordinate geometry.',
      icon: 'school-outline',
      topics: [
        'Arithmetic Progression (AP): Nth Term and Sum of N Terms Formulas',
        'Geometric Progression (GP): Nth Term, Sum of N Terms, and Infinite GP',
        'Harmonic Progression (HP) and AM-GM-HM Inequality Relationship',
        'Coordinate Geometry: Distance Formula, Section Formula, and Midpoint',
        'Slope of a Line, Equation of Line, and Intercepts',
        'Modular Arithmetic Applications in Cryptography and Computer Science',
      ],
    },

    // --- STAGE 5: COMBINED APTITUDE PRACTICE (SECTION 3 OF SPEC) ---
    {
      title: 'Combined: Numbers, Fractions & Percentages',
      description: 'Synthesizing number properties with percentages and fractions.',
      icon: 'layers-outline',
      topics: [
        'Number System + HCF + LCM Integrated Word Problems',
        'Fractions + Simplification + Percentage Multi-Step Equations',
        'Percentage + Ratio + Average Combined Scenarios',
        'Number System + Algebra + Remainder Equations',
      ],
    },
    {
      title: 'Combined: Commercial Mathematics',
      description: 'Integrating profit, discount, interest, and partnership.',
      icon: 'briefcase-outline',
      topics: [
        'Percentage + Profit/Loss + Discount Multi-Transaction Cases',
        'Percentage + Simple Interest + Compound Interest Comparison',
        'Ratio + Partnership + Profit/Loss Complex Allotments',
        'Ratio + Average + Ages Multi-Variable Equations',
      ],
    },
    {
      title: 'Combined: Work, Motion & Mixtures',
      description: 'Combining speed, work, pipes, trains, and alligation.',
      icon: 'bicycle-outline',
      topics: [
        'Ratio + Time & Work + Pipes and Cisterns Synergies',
        'Ratio + Speed + Time & Distance Combined Dynamics',
        'Speed + Trains + Boats and Streams Relative Motion',
        'Mixture + Ratio + Percentage + Alligation Formulations',
      ],
    },
    {
      title: 'Combined: Geometry, Algebra & Probability',
      description: 'Synthesizing algebraic modeling with shapes and counting.',
      icon: 'prism-outline',
      topics: [
        'Permutation + Combination + Probability High-Yield Drills',
        'Algebra + Ages + Number Problem Mathematical Modeling',
        'Geometry + Mensuration + Coordinate Geometry Spatial Tests',
        'Percentage + Ratio + Average + Data Interpretation Synthesis',
        'Advanced Mixed Quantitative Integrated Sets',
      ],
    },

    // --- STAGE 6: COMPANY-LEVEL PROGRESSION (SECTION 6 OF SPEC) ---
    {
      title: 'Company-Level: Levels 1 to 4',
      description: 'Structured difficulty ladder from single topic to three-topic blend.',
      icon: 'trophy-outline',
      topics: [
        'Level 1: Single-Topic High-Speed Accuracy Drills',
        'Level 2: Subtopic Mixed Cross-Over Challenges',
        'Level 3: Two-Topic Combination Problem Solving',
        'Level 4: Three-Topic Multi-Step Case Scenarios',
      ],
    },
    {
      title: 'Company-Level: Levels 5 to 7',
      description: 'Multi-topic blend, unknown-topic blind test, and company exam style.',
      icon: 'medal-outline',
      topics: [
        'Level 5: Multi-Topic Comprehensive Aptitude Challenges',
        'Level 6: Unknown-Topic Questions (Concept Blind Identification)',
        'Level 7: Full Company-Style Speed Assessment (TCS, Infosys, Wipro, Accenture)',
      ],
    },
    {
      title: 'Full Quantitative Mix',
      description: 'Comprehensive blind aptitude test with no chapter labels or hints.',
      icon: 'ribbon-outline',
      topics: [
        'Full Quantitative Mix: Set 1 (Blind Mixed Practice - No Chapter Hints)',
        'Full Quantitative Mix: Set 2 (Time-Pressured 60-Second Challenge)',
        'Full Quantitative Mix: Set 3 (Placement Exam Simulation Test)',
        'Full Quantitative Mix: Set 4 (Product Company Technical Aptitude)',
      ],
    },
  ],
};
