import { CourseRoadmapSeed } from './types';

export const dsaRoadmap: CourseRoadmapSeed = {
  courseId: 'dsa',
  modules: [
    {
      title: 'Programming fundamentals for DSA',
      description: 'Language semantics, pointers/references, pass-by-value/reference, and memory layout.',
      icon: 'terminal-outline',
      topics: [
        'Memory addresses and pointers',
        'Stack vs Heap allocation',
        'Pass by value vs pass by reference',
        'Basic I/O efficiency',
        'Math primitives for coding',
      ],
    },
    {
      title: 'Complexity analysis',
      description: 'Evaluating algorithm efficiency across time and auxiliary space dimensions.',
      icon: 'speedometer-outline',
      topics: [
        'Big O, Omega, and Theta notation',
        'Time complexity calculation',
        'Space complexity calculation',
        'Amortized analysis',
        'Common growth rates comparison',
      ],
    },
    {
      title: 'Arrays',
      description: 'Contiguous memory access, two-pointer techniques, and sliding window patterns.',
      icon: 'grid-outline',
      topics: [
        '1D and 2D arrays',
        'Prefix sum technique',
        'Two pointers pattern',
        'Sliding window technique',
        'Kadanes algorithm',
        'Array rotations and permutations',
      ],
    },
    {
      title: 'Strings',
      description: 'String manipulation, pattern matching, anagrams, and palindrome validation.',
      icon: 'text-outline',
      topics: [
        'String immutability and builders',
        'Palindrome verification',
        'Anagram detection',
        'Substrings and subsequences',
        'Pattern matching basics',
      ],
    },
    {
      title: 'Searching',
      description: 'Linear scanning, binary search variants, and search space reduction.',
      icon: 'search-outline',
      topics: [
        'Linear search',
        'Binary search algorithm',
        'Lower bound and upper bound',
        'Binary search on answer',
        'Rotated sorted array search',
      ],
    },
    {
      title: 'Sorting',
      description: 'Comparison and non-comparison sorting algorithms and stability guarantees.',
      icon: 'swap-vertical-outline',
      topics: [
        'Bubble, Selection, and Insertion sort',
        'Merge sort',
        'Quick sort and partition schemes',
        'Counting sort and Radix sort',
        'Sorting stability and in-place sorting',
      ],
    },
    {
      title: 'Recursion',
      description: 'Recursive call stacks, base conditions, recurrence relations, and tree branches.',
      icon: 'git-merge-outline',
      topics: [
        'Call stack visualization',
        'Base cases and recursion leap of faith',
        'Recurrence relations',
        'Tower of Hanoi',
        'Subset and subsequence generation',
      ],
    },
    {
      title: 'Backtracking',
      description: 'Exhaustive state space search with systematic pruning and undo operations.',
      icon: 'arrow-undo-outline',
      topics: [
        'State space trees',
        'N-Queens problem',
        'Sudoku solver',
        'Permutations and combinations',
        'Word search on grids',
      ],
    },
    {
      title: 'Linked Lists',
      description: 'Dynamic node chains, pointers, reversals, cycle detection, and merging.',
      icon: 'link-outline',
      topics: [
        'Singly linked list',
        'Doubly and circular linked lists',
        'Reversing a linked list',
        'Detecting cycles (Floyds Tortoise & Hare)',
        'Merge two sorted lists',
        'LRU Cache design basics',
      ],
    },
    {
      title: 'Stack',
      description: 'LIFO access pattern, expression evaluation, and monotonic stack techniques.',
      icon: 'layers-outline',
      topics: [
        'Stack implementation via array & list',
        'Balanced parentheses check',
        'Infix, prefix, and postfix notation',
        'Next greater element',
        'Monotonic stack pattern',
      ],
    },
    {
      title: 'Queue',
      description: 'FIFO processing, circular buffers, deques, and monotonic queue patterns.',
      icon: 'file-tray-full-outline',
      topics: [
        'Queue implementation',
        'Circular queue',
        'Double-ended queue (Deque)',
        'Sliding window maximum using deque',
        'Queue using stacks',
      ],
    },
    {
      title: 'Hashing',
      description: 'Hash functions, collision resolution, lookup optimization, and frequency maps.',
      icon: 'finger-print-outline',
      topics: [
        'Hash functions and collisions',
        'Chaining and Open Addressing',
        'Hash maps and Hash sets',
        'Two Sum and frequency counting',
        'Subarray sum equals K',
      ],
    },
    {
      title: 'Trees',
      description: 'Hierarchical node graphs, traversals, depth, height, and diameter.',
      icon: 'git-network-outline',
      topics: [
        'Binary tree representation',
        'Preorder, Inorder, and Postorder traversals',
        'Level order traversal (BFS)',
        'Height and diameter of a tree',
        'Lowest Common Ancestor (LCA)',
      ],
    },
    {
      title: 'Binary Search Trees',
      description: 'Ordered binary tree properties, search, insertion, deletion, and validation.',
      icon: 'git-branch-outline',
      topics: [
        'BST properties and invariants',
        'Search, insert, and delete in BST',
        'Validate binary search tree',
        'Kth smallest/largest in BST',
        'Inorder successor and predecessor',
      ],
    },
    {
      title: 'Heap / Priority Queue',
      description: 'Complete binary tree arrays, min/max heaps, heapify, and top-K queries.',
      icon: 'filter-outline',
      topics: [
        'Min-heap and Max-heap',
        'Heapify operation',
        'Heap sort',
        'Kth largest element',
        'Merge K sorted lists',
      ],
    },
    {
      title: 'Graphs',
      description: 'Adjacency lists/matrices, traversals, topological sorting, and shortest paths.',
      icon: 'share-social-outline',
      topics: [
        'Graph representations (List vs Matrix)',
        'Breadth First Search (BFS)',
        'Depth First Search (DFS)',
        'Cycle detection in directed & undirected',
        'Topological sort (Kahns algorithm)',
        'Dijkstras shortest path algorithm',
      ],
    },
    {
      title: 'Greedy Algorithms',
      description: 'Making locally optimal choices to achieve global optimization.',
      icon: 'ribbon-outline',
      topics: [
        'Greedy choice property',
        'Activity selection problem',
        'Fractional knapsack',
        'Huffman coding concepts',
        'Minimum spanning tree (Kruskal & Prim)',
      ],
    },
    {
      title: 'Dynamic Programming',
      description: 'Overlapping subproblems, optimal substructure, memoization, and tabulation.',
      icon: 'cube-outline',
      topics: [
        'Memoization (Top-down) vs Tabulation (Bottom-up)',
        '0/1 Knapsack problem',
        'Longest Common Subsequence (LCS)',
        'Longest Increasing Subsequence (LIS)',
        'Matrix chain multiplication & grid DP',
      ],
    },
    {
      title: 'Bit Manipulation',
      description: 'Low-level binary operations, bit masks, XOR properties, and subset tricks.',
      icon: 'hardware-chip-outline',
      topics: [
        'Bitwise AND, OR, XOR, NOT, Shifts',
        'Checking and setting kth bit',
        'Counting set bits (Brian Kernighan)',
        'Single Number using XOR',
        'Power of two check',
      ],
    },
    {
      title: 'Advanced problem solving',
      description: 'Disjoint Set Union (Union-Find), Trie structures, and segment concepts.',
      icon: 'bulb-outline',
      topics: [
        'Disjoint Set Union (Union-Find)',
        'Path compression & union by rank',
        'Trie (Prefix tree) implementation',
        'Prefix matching using Trie',
        'Meet in the middle technique',
      ],
    },
    {
      title: 'Interview problems',
      description: 'Top recurring technical interview challenges from tier-1 engineering companies.',
      icon: 'briefcase-outline',
      topics: [
        'Trapping rain water',
        'LRU and LFU cache design',
        'Word ladder and shortest transformations',
        'Course schedule dependencies',
        'Median of two sorted arrays',
      ],
    },
    {
      title: 'Competitive programming basics',
      description: 'Fast I/O, modular arithmetic, test case generation, and contest mindset.',
      icon: 'trophy-outline',
      topics: [
        'Fast I/O and execution limits',
        'Modular arithmetic and exponentiation',
        'Sieve of Eratosthenes',
        'Handling edge cases under pressure',
        'Contest strategies and time budgeting',
      ],
    },
  ],
};
