import { CourseRoadmapSeed } from './types';

export const pythonRoadmap: CourseRoadmapSeed = {
  courseId: 'python',
  modules: [
    {
      title: 'Python Fundamentals',
      description: 'Core concepts, interpreter setup, syntax rules, and basic I/O operations.',
      icon: 'code-outline',
      topics: [
        'What is Python?',
        'Python installation',
        'Python interpreter',
        'Running Python programs',
        'Python syntax',
        'Comments',
        'Indentation',
        'print()',
        'input()',
      ],
    },
    {
      title: 'Variables & Data Types',
      description: 'Memory allocation, dynamic typing, primitive data types, and conversions.',
      icon: 'cube-outline',
      topics: [
        'Variables',
        'Naming rules',
        'int',
        'float',
        'string',
        'boolean',
        'None',
        'type()',
        'type conversion',
      ],
    },
    {
      title: 'Operators',
      description: 'Mathematical, logical, bitwise, and membership operators in Python.',
      icon: 'calculator-outline',
      topics: [
        'Arithmetic operators',
        'Assignment operators',
        'Comparison operators',
        'Logical operators',
        'Identity operators',
        'Membership operators',
        'Bitwise operators',
      ],
    },
    {
      title: 'Strings',
      description: 'Text processing, indexing, string slicing, modern f-strings, and methods.',
      icon: 'text-outline',
      topics: [
        'String creation',
        'Indexing',
        'Slicing',
        'String methods',
        'String formatting',
        'f-strings',
        'Escape characters',
      ],
    },
    {
      title: 'Conditional Statements',
      description: 'Decision making with if, elif, else, and ternary conditional expressions.',
      icon: 'git-branch-outline',
      topics: [
        'if',
        'elif',
        'else',
        'Nested conditions',
        'Conditional expressions',
      ],
    },
    {
      title: 'Loops',
      description: 'Iteration mastery with while and for loops, range sequences, and loop control.',
      icon: 'repeat-outline',
      topics: [
        'for loop',
        'while loop',
        'range()',
        'break',
        'continue',
        'pass',
        'nested loops',
      ],
    },
    {
      title: 'Lists',
      description: 'Dynamic ordered arrays, slicing, mutation, methods, and comprehensions.',
      icon: 'list-outline',
      topics: [
        'Creating lists',
        'Indexing',
        'Slicing',
        'Adding elements',
        'Removing elements',
        'List methods',
        'List iteration',
        'Nested lists',
        'List comprehensions',
      ],
    },
    {
      title: 'Tuples',
      description: 'Immutable sequences, tuple packing, unpacking, and performance advantages.',
      icon: 'lock-closed-outline',
      topics: [
        'Creating tuples',
        'Indexing',
        'Slicing',
        'Tuple methods',
        'Packing',
        'Unpacking',
      ],
    },
    {
      title: 'Sets',
      description: 'Unordered unique collections and mathematical set operations.',
      icon: 'shapes-outline',
      topics: [
        'Creating sets',
        'Adding/removing elements',
        'Set operations',
        'Union',
        'Intersection',
        'Difference',
        'Symmetric difference',
      ],
    },
    {
      title: 'Dictionaries',
      description: 'Key-value associative stores, hashing, dict comprehension, and nesting.',
      icon: 'book-outline',
      topics: [
        'Keys and values',
        'Creating dictionaries',
        'Accessing values',
        'Adding/updating values',
        'Removing values',
        'Dictionary methods',
        'Iteration',
        'Nested dictionaries',
      ],
    },
    {
      title: 'Functions',
      description: 'Modular reusability, parameters, *args, **kwargs, recursion, and lambdas.',
      icon: 'construct-outline',
      topics: [
        'Defining functions',
        'Parameters',
        'Arguments',
        'Return values',
        'Default arguments',
        'Keyword arguments',
        '*args',
        '**kwargs',
        'Scope',
        'Recursion',
        'Lambda functions',
      ],
    },
    {
      title: 'Exception Handling',
      description: 'Defensive programming, handling runtime errors gracefully with try-except.',
      icon: 'alert-circle-outline',
      topics: [
        'Errors',
        'Exceptions',
        'try',
        'except',
        'else',
        'finally',
        'raise',
        'Custom exceptions',
      ],
    },
    {
      title: 'File Handling',
      description: 'Filesystem I/O, context managers, reading and writing text, CSV, and JSON.',
      icon: 'folder-open-outline',
      topics: [
        'Opening files',
        'Reading files',
        'Writing files',
        'Appending files',
        'with statement',
        'CSV files',
        'JSON files',
      ],
    },
    {
      title: 'Object-Oriented Programming',
      description: 'Classes, instance & class state, inheritance, encapsulation, and polymorphism.',
      icon: 'layers-outline',
      topics: [
        'Classes',
        'Objects',
        '__init__',
        'Instance variables',
        'Class variables',
        'Methods',
        'Inheritance',
        'Multiple inheritance',
        'Encapsulation',
        'Polymorphism',
        'Abstraction',
        'Magic methods',
      ],
    },
    {
      title: 'Modules & Packages',
      description: 'Code distribution, namespacing, imports, pip, and virtual environments.',
      icon: 'cube-outline',
      topics: [
        'import',
        'from import',
        'Creating modules',
        'Creating packages',
        '__init__.py',
        'pip',
        'virtual environments',
      ],
    },
    {
      title: 'Advanced Python',
      description: 'Decorators, closures, generators, iterators, and functional primitives.',
      icon: 'flash-outline',
      topics: [
        'Iterators',
        'Generators',
        'Decorators',
        'Closures',
        'Context managers',
        'map()',
        'filter()',
        'reduce()',
        'enumerate()',
        'zip()',
        'comprehensions',
      ],
    },
    {
      title: 'Python Data Structures',
      description: 'Practical implementations of linear and non-linear data structures in Python.',
      icon: 'file-tray-stacked-outline',
      topics: [
        'Stack',
        'Queue',
        'Deque',
        'Linked list',
        'Hash table concepts',
        'Trees',
        'Graph concepts',
      ],
    },
    {
      title: 'Algorithms',
      description: 'Core sorting and searching techniques, recursion, and complexity evaluation.',
      icon: 'speedometer-outline',
      topics: [
        'Searching',
        'Sorting',
        'Recursion',
        'Time complexity',
        'Space complexity',
        'Big O notation',
      ],
    },
    {
      title: 'Database Programming',
      description: 'Interfacing with SQLite and relational stores from Python code.',
      icon: 'server-outline',
      topics: [
        'SQL from Python',
        'SQLite',
        'Database connections',
        'CRUD',
        'Transactions',
        'Parameterized queries',
      ],
    },
    {
      title: 'Python for Web Development',
      description: 'HTTP communication, RESTful services, and consumption of JSON web APIs.',
      icon: 'globe-outline',
      topics: [
        'HTTP basics',
        'APIs',
        'JSON APIs',
        'Requests',
        'REST APIs',
        'Authentication concepts',
      ],
    },
    {
      title: 'Python for Automation',
      description: 'Scripting system commands, directory walkers, and background process control.',
      icon: 'hardware-chip-outline',
      topics: [
        'OS module',
        'pathlib',
        'shutil',
        'subprocess',
        'Automation scripts',
        'File automation',
      ],
    },
    {
      title: 'Python Testing',
      description: 'Unit testing frameworks, test assertions, mocking, and automated verification.',
      icon: 'checkmark-circle-outline',
      topics: [
        'Unit testing',
        'unittest',
        'pytest concepts',
        'Assertions',
        'Test organization',
        'Mocking concepts',
      ],
    },
    {
      title: 'Python for Data',
      description: 'Foundations of numerical computing and analytical data manipulation.',
      icon: 'pie-chart-outline',
      topics: [
        'NumPy basics',
        'Pandas basics',
        'DataFrames',
        'Data cleaning',
        'Matplotlib basics',
      ],
    },
    {
      title: 'Professional Python',
      description: 'Industry best practices, type annotations, PEP 8 styling, and documentation.',
      icon: 'shield-checkmark-outline',
      topics: [
        'Project structure',
        'Environment variables',
        'requirements.txt',
        'Logging',
        'Debugging',
        'Code quality',
        'PEP 8',
        'Type hints',
        'Documentation',
      ],
    },
    {
      title: 'Real Projects',
      description: 'Full end-to-end portfolio projects applying all learned Python skills.',
      icon: 'trophy-outline',
      topics: [
        'Calculator',
        'To-do application',
        'Number guessing game',
        'Contact manager',
        'Expense tracker',
        'File organizer',
        'Web API project',
        'Database project',
        'Automation project',
        'Final Python project',
      ],
    },
  ],
};
