import { CourseRoadmapSeed } from './types';

export const htmlRoadmap: CourseRoadmapSeed = {
  courseId: 'html',
  modules: [
    { title: 'HTML fundamentals', description: 'Web page mechanics, markup syntax, tags, elements, and attributes.', icon: 'code-slash-outline', topics: ['What is HTML and how browsers render markup', 'Tags vs Elements vs Attributes', 'Self-closing (void) elements', 'Creating your first index.html'] },
    { title: 'Document structure', description: 'HTML5 boilerplates, <!DOCTYPE html>, <html>, <head>, and <body>.', icon: 'browsers-outline', topics: ['DOCTYPE declaration significance', 'The <head> element and <meta> tags', 'The <title> and favicon setup', 'Character encoding (UTF-8) and viewport'] },
    { title: 'Headings', description: 'Heading hierarchy: <h1> to <h6>, document outlines, and accessibility guidelines.', icon: 'text-outline', topics: ['h1 through h6 tag hierarchy', 'SEO importance of single h1 per page', 'Visual size vs structural importance'] },
    { title: 'Paragraphs', description: 'Body text formatting, <p>, line breaks <br>, horizontal rules <hr>, and typography tags.', icon: 'reader-outline', topics: ['Paragraph <p> tags', 'Line breaks (<br>) and rules (<hr>)', 'Text emphasis: <strong>, <em>, <mark>, <small>'] },
    { title: 'Links', description: 'Hyperlinks, <a> tag, relative vs absolute URLs, target attributes, and anchors.', icon: 'link-outline', topics: ['Anchor tag <a> and href attribute', 'Absolute vs Relative URLs', 'target="_blank" and rel="noopener noreferrer"', 'In-page anchor navigation (id jumping)'] },
    { title: 'Images', description: 'Embedding images with <img>, src, alt text, responsive attributes, and modern formats.', icon: 'image-outline', topics: ['The <img> element and src attribute', 'The alt attribute for accessibility and SEO', 'Image dimensions: width and height', 'Modern WebP and SVG image formats'] },
    { title: 'Lists', description: 'Organizing content with ordered (<ol>), unordered (<ul>), and description (<dl>) lists.', icon: 'list-outline', topics: ['Unordered lists (<ul> and <li>)', 'Ordered lists (<ol> with type and start)', 'Nested lists hierarchy', 'Description lists (<dl>, <dt>, <dd>)'] },
    { title: 'Tables', description: 'Tabular data presentation: <table>, <tr>, <th>, <td>, thead, tbody, and colspans.', icon: 'grid-outline', topics: ['Basic table structure: <table>, <tr>, <td>', 'Headers with <th> and scope attribute', 'Table sections: <thead>, <tbody>, <tfoot>', 'Spanning cells: colspan and rowspan'] },
    { title: 'Forms', description: 'User input collection: <form>, action, method (GET/POST), and labels.', icon: 'create-outline', topics: ['The <form> element and action/method', 'Accessible labeling with <label for>', 'Fieldset and <legend> grouping', 'Form submission lifecycle'] },
    { title: 'Inputs', description: 'Interactive controls: text, email, password, radio, checkbox, date, range, and buttons.', icon: 'options-outline', topics: ['Text, password, and email input types', 'Radio buttons and checkboxes (name group)', 'Number, range, date, and color pickers', '<textarea> and <select> dropdowns', 'Input validation attributes (required, min, max, pattern)'] },
    { title: 'Semantic HTML', description: 'Meaningful structural tags: <header>, <nav>, <main>, <article>, <section>, <footer>.', icon: 'construct-outline', topics: ['Why semantics matter for screens and bots', '<header>, <nav>, and <footer> tags', '<main>, <article>, and <section>', '<aside>, <figure>, and <figcaption>'] },
    { title: 'Audio/video', description: 'Native multimedia playback: <audio>, <video>, controls, sources, and subtitles.', icon: 'videocam-outline', topics: ['Embedding video with <video> and controls', 'Multiple <source> formats for fallback', 'Embedding audio with <audio>', 'Subtitles and captions with <track>'] },
    { title: 'Accessibility', description: 'WCAG principles, ARIA roles, labels, tabindex, and screen reader friendliness.', icon: 'accessibility-outline', topics: ['WCAG guidelines overview', 'ARIA landmarks and attributes (aria-label, role)', 'Keyboard navigation and tabindex', 'Screen reader testing essentials'] },
    { title: 'SEO basics', description: 'Search Engine Optimization markup: meta descriptions, Open Graph, and canonicals.', icon: 'trending-up-outline', topics: ['Title tags and meta descriptions', 'Open Graph meta tags for social sharing', 'Canonical link tags', 'Structured data (JSON-LD basics)'] },
    { title: 'HTML5', description: 'Modern HTML5 APIs: canvas, SVG, geolocation, drag-and-drop, and web storage.', icon: 'sparkles-outline', topics: ['Canvas vs SVG embedding', 'Local Storage and Session Storage in HTML', 'HTML5 Drag and Drop API', 'HTML5 dialog and template elements'] },
    { title: 'Projects', description: 'Building semantic, accessible real-world web pages.', icon: 'trophy-outline', topics: ['Personal Profile Page', 'Product Landing Page', 'Multi-step Survey Form', 'Technical Documentation Page', 'Final HTML Capstone Project'] },
  ],
};

export const cssRoadmap: CourseRoadmapSeed = {
  courseId: 'css',
  modules: [
    { title: 'CSS fundamentals', description: 'Cascading Style Sheets: inline, internal, external CSS, and syntax rules.', icon: 'color-palette-outline', topics: ['What is CSS and how browsers parse rules', 'Inline, Internal (<style>), and External (.css)', 'CSS rule syntax (selector, property, value)', 'Cascading order and inheritance basics'] },
    { title: 'Selectors', description: 'Targeting elements: element, class, ID, attribute, pseudo-classes, and pseudo-elements.', icon: 'finger-print-outline', topics: ['Universal, element, class (.), and ID (#) selectors', 'Combinators (descendant, child >, adjacent +)', 'Attribute selectors ([type="text"])', 'Pseudo-classes (:hover, :focus, :nth-child)', 'Pseudo-elements (::before, ::after)', 'CSS Specificity calculation (0-0-0-0)'] },
    { title: 'Colors', description: 'Color representations: named, HEX, RGB/RGBA, HSL/HSLA, and color accessibility.', icon: 'color-filter-outline', topics: ['Color names and HEX (#RRGGBB)', 'rgb() and rgba() with alpha opacity', 'hsl() and hsla() for intuitive shades', 'Color contrast ratios and WCAG compliance'] },
    { title: 'Units', description: 'Measurement units: absolute (px, pt) vs relative (%, em, rem, vw, vh, ch).', icon: 'resize-outline', topics: ['Pixels (px) as absolute units', 'Percentages (%) for fluid layouts', 'em vs rem relative typography', 'Viewport units: vw, vh, vmin, vmax'] },
    { title: 'Box model', description: 'The core layout model: content, padding, border, margin, and box-sizing.', icon: 'square-outline', topics: ['Box model layers: content, padding, border, margin', 'box-sizing: border-box vs content-box', 'Margin collapsing mechanics', 'Outline vs border differences'] },
    { title: 'Display', description: 'Rendering flow: block, inline, inline-block, none, and visibility: hidden.', icon: 'eye-outline', topics: ['Block-level elements behavior', 'Inline and inline-block elements', 'display: none vs visibility: hidden', 'display: contents overview'] },
    { title: 'Position', description: 'Document positioning schemes: static, relative, absolute, fixed, and sticky.', icon: 'pin-outline', topics: ['Static (default) positioning', 'Relative positioning and offsets (top, left)', 'Absolute positioning within containing block', 'Fixed positioning (navigation bars, overlays)', 'Sticky positioning (scroll headers)', 'z-index and stacking contexts'] },
    { title: 'Flexbox', description: 'One-dimensional layouts: flex containers, axis, justify-content, align-items, flex-wrap.', icon: 'reorder-four-outline', topics: ['display: flex and Main vs Cross axis', 'flex-direction and flex-wrap (flex-flow)', 'justify-content and align-items', 'flex-grow, flex-shrink, and flex-basis', 'gap property for spacing', 'Centering elements effortlessly with Flexbox'] },
    { title: 'Grid', description: 'Two-dimensional layouts: grid-template-columns/rows, fr units, areas, auto-fit/fill.', icon: 'grid-outline', topics: ['display: grid container basics', 'grid-template-columns and the fr unit', 'repeat() and minmax() functions', 'auto-fit vs auto-fill responsive grids', 'grid-template-areas for layout scaffolding', 'grid-column and grid-row spanning'] },
    { title: 'Typography', description: 'Text styling: font-family, font-weight, line-height, Google Fonts, and text-align.', icon: 'text-outline', topics: ['font-family and fallback font stacks', 'Web fonts with Google Fonts (@import, <link>)', 'font-size, font-weight, and line-height', 'text-align, text-decoration, and letter-spacing', 'text-overflow: ellipsis for truncating'] },
    { title: 'Responsive design', description: 'Mobile-first philosophy, fluid viewports, responsive images, and fluid containers.', icon: 'phone-portrait-outline', topics: ['Mobile-first design methodology', 'Fluid widths (max-width: 100%)', 'Responsive images (srcset and <picture>)', 'Breakpoints strategy'] },
    { title: 'Media queries', description: 'Conditional CSS: @media rules, min-width, max-width, orientation, and dark mode.', icon: 'laptop-outline', topics: ['@media rule syntax (min-width, max-width)', 'Common device screen breakpoints', 'Combining conditions (and, or, not)', 'prefers-color-scheme for dark mode'] },
    { title: 'Animations', description: 'CSS keyframe animations: @keyframes, animation-name, duration, timing-function, iterations.', icon: 'flame-outline', topics: ['@keyframes rule definition', 'animation-duration, delay, and iteration-count', 'animation-timing-function (ease, cubic-bezier)', 'animation-fill-mode (forwards, backwards)'] },
    { title: 'Transitions', description: 'Smooth property interpolation: transition-property, duration, timing, and delays.', icon: 'swap-horizontal-outline', topics: ['transition shorthand property', 'Timing functions (ease-in, ease-out, linear)', 'Transitioning colors and opacities', 'Performance: which properties to transition'] },
    { title: 'Transforms', description: '2D/3D matrix transforms: translate, scale, rotate, skew, and transform-origin.', icon: 'move-outline', topics: ['translate(x, y) for performant motion', 'scale(x, y) for size changes', 'rotate() and skew()', '3D transforms and perspective', 'transform-origin anchor manipulation'] },
    { title: 'Variables', description: 'Custom properties: --var syntax, var() function, scope, and theming.', icon: 'code-outline', topics: ['Declaring CSS variables on :root', 'Consuming variables with var() and fallbacks', 'Scoped variables within components', 'Dynamic runtime theming with CSS variables'] },
    { title: 'Advanced CSS', description: 'Modern CSS: clamp(), aspect-ratio, subgrid, backdrop-filter, and CSS nesting.', icon: 'sparkles-outline', topics: ['Fluid sizing with clamp(), min(), and max()', 'aspect-ratio property', 'backdrop-filter: blur() glassmorphism', 'Native CSS nesting syntax', 'BEM naming methodology basics'] },
    { title: 'Projects', description: 'Hands-on responsive web design projects from scratch.', icon: 'trophy-outline', topics: ['Responsive Navbar with Mobile Hamburger', 'Pricing Cards Component with Flexbox', 'Photo Gallery with CSS Grid', 'Animated Dashboard Interface', 'Final Portfolio Website Project'] },
  ],
};
