/**
 * Global Course Visual Identity Configuration
 * Signature colors, icons, badge tags, and ambient motif styling for each course.
 * Visual identities are configuration-driven, keeping all courses visually cohesive.
 */

export interface CourseVisualIdentity {
  courseId: string;
  name: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  bgTint: string;
  icon: string;
  badge: string;
  visualMotif: 'pythonic' | 'graph_tree' | 'branch' | 'grid' | 'layers' | 'terminal' | 'network' | 'reactive_nodes' | 'math' | 'dialogue' | 'default';
  tagline: string;
}

export const COURSE_IDENTITIES: Record<string, CourseVisualIdentity> = {
  python: {
    courseId: 'python',
    name: 'Python',
    primaryColor: '#3776AB',
    secondaryColor: '#FFD438',
    accentColor: '#4B8BBE',
    bgTint: '#EFF6FF',
    icon: 'language-python',
    badge: 'Pythonic Mastery',
    visualMotif: 'pythonic',
    tagline: 'Clean syntax, dynamic power, and expressive paradigms.',
  },
  dsa: {
    courseId: 'dsa',
    name: 'DSA',
    primaryColor: '#DC2626',
    secondaryColor: '#FCA5A5',
    accentColor: '#EF4444',
    bgTint: '#FEF2F2',
    icon: 'graph-outline',
    badge: 'Structures & Big-O',
    visualMotif: 'graph_tree',
    tagline: 'Optimal memory layouts, asymptotic efficiency, and interview problem-solving.',
  },
  git: {
    courseId: 'git',
    name: 'Git',
    primaryColor: '#F05032',
    secondaryColor: '#FDBA74',
    accentColor: '#EA580C',
    bgTint: '#FFF7ED',
    icon: 'git',
    badge: 'Distributed VCS',
    visualMotif: 'branch',
    tagline: 'Branching graphs, atomic commits, rebasing, and team workflows.',
  },
  sql: {
    courseId: 'sql',
    name: 'SQL',
    primaryColor: '#0284C7',
    secondaryColor: '#7DD3FC',
    accentColor: '#0369A1',
    bgTint: '#F0F9FF',
    icon: 'database',
    badge: 'Relational Schemas',
    visualMotif: 'grid',
    tagline: 'ACID guarantees, indexing strategies, joins, and declarative queries.',
  },
  django: {
    courseId: 'django',
    name: 'Django',
    primaryColor: '#092E20',
    secondaryColor: '#34D399',
    accentColor: '#059669',
    bgTint: '#ECFDF5',
    icon: 'alpha-d-box-outline',
    badge: 'Batteries Included',
    visualMotif: 'layers',
    tagline: 'Enterprise web framework, ORM, migrations, and REST APIs.',
  },
  ml_developer: {
    courseId: 'ml_developer',
    name: 'ML Developer',
    primaryColor: '#7C3AED',
    secondaryColor: '#C4B5FD',
    accentColor: '#6D28D9',
    bgTint: '#F5F3FF',
    icon: 'brain',
    badge: 'Intelligence & Tensors',
    visualMotif: 'graph_tree',
    tagline: 'NumPy, Scikit-learn, gradient descent, and predictive modeling.',
  },
  linux: {
    courseId: 'linux',
    name: 'Linux',
    primaryColor: '#FCC624',
    secondaryColor: '#334155',
    accentColor: '#D97706',
    bgTint: '#FEFCE8',
    icon: 'linux',
    badge: 'Command Line Power',
    visualMotif: 'terminal',
    tagline: 'Shell pipelines, process tree, permissions, and system administration.',
  },
  frappe: {
    courseId: 'frappe',
    name: 'Frappe',
    primaryColor: '#2563EB',
    secondaryColor: '#93C5FD',
    accentColor: '#1D4ED8',
    bgTint: '#EFF6FF',
    icon: 'layers-outline',
    badge: 'DocType Architecture',
    visualMotif: 'layers',
    tagline: 'Meta-data driven enterprise models, workflows, and ERPNext.',
  },
  aptitude: {
    courseId: 'aptitude',
    name: 'Aptitude',
    primaryColor: '#D97706',
    secondaryColor: '#FDE68A',
    accentColor: '#B45309',
    bgTint: '#FFFBEB',
    icon: 'calculator-variant',
    badge: 'Quantitative Logic',
    visualMotif: 'math',
    tagline: 'Fast calculations, speed math, percentages, and ratio mastery.',
  },
  reasoning: {
    courseId: 'reasoning',
    name: 'Reasoning',
    primaryColor: '#4F46E5',
    secondaryColor: '#C7D2FE',
    accentColor: '#4338CA',
    bgTint: '#EEF2FF',
    icon: 'head-snowflake-outline',
    badge: 'Logical Deduction',
    visualMotif: 'graph_tree',
    tagline: 'Analytical puzzles, seating arrangements, and spatial reasoning.',
  },
  verbal_english: {
    courseId: 'verbal_english',
    name: 'Verbal English',
    primaryColor: '#0D9488',
    secondaryColor: '#99F6E4',
    accentColor: '#0F766E',
    bgTint: '#F0FDFA',
    icon: 'book-open-page-variant',
    badge: 'Grammar & Placement',
    visualMotif: 'dialogue',
    tagline: 'Sentence correction, error spotting, idioms, and reading comprehension.',
  },
  english_speaking: {
    courseId: 'english_speaking',
    name: 'English Speaking',
    primaryColor: '#059669',
    secondaryColor: '#A7F3D0',
    accentColor: '#047857',
    bgTint: '#ECFDF5',
    icon: 'microphone-message',
    badge: 'Fluent Conversations',
    visualMotif: 'dialogue',
    tagline: 'Workplace speaking, pronunciation, scenario roleplays, and confidence.',
  },
  html: {
    courseId: 'html',
    name: 'HTML',
    primaryColor: '#E34F26',
    secondaryColor: '#FDBA74',
    accentColor: '#C2410C',
    bgTint: '#FFF7ED',
    icon: 'language-html5',
    badge: 'Semantic Web',
    visualMotif: 'grid',
    tagline: 'Accessible markup, document hierarchy, and SEO foundations.',
  },
  css: {
    courseId: 'css',
    name: 'CSS',
    primaryColor: '#1572B6',
    secondaryColor: '#BAE6FD',
    accentColor: '#0369A1',
    bgTint: '#F0F9FF',
    icon: 'language-css3',
    badge: 'Modern Layouts',
    visualMotif: 'layers',
    tagline: 'Flexbox, Grid, transitions, variables, and responsive elegance.',
  },
  javascript: {
    courseId: 'javascript',
    name: 'JavaScript',
    primaryColor: '#CA8A04',
    secondaryColor: '#FEF08A',
    accentColor: '#A16207',
    bgTint: '#FEFCE8',
    icon: 'language-javascript',
    badge: 'ES6+ & Asynchronous',
    visualMotif: 'pythonic',
    tagline: 'Closures, event loop, promises, async/await, and DOM dynamics.',
  },
  system_design: {
    courseId: 'system_design',
    name: 'System Design',
    primaryColor: '#0284C7',
    secondaryColor: '#38BDF8',
    accentColor: '#6366F1',
    bgTint: '#F0F9FF',
    icon: 'server-network',
    badge: 'Distributed Systems',
    visualMotif: 'network',
    tagline: 'L0 to L60: load balancers, caching tiers, sharding, and fault tolerance.',
  },
  react: {
    courseId: 'react',
    name: 'React',
    primaryColor: '#00D8FE',
    secondaryColor: '#61DAFB',
    accentColor: '#0284C7',
    bgTint: '#F0FDFF',
    icon: 'react',
    badge: 'Component Tree',
    visualMotif: 'reactive_nodes',
    tagline: 'Fiber reconciler, Hooks, TanStack Query, and Full-Stack Next.js.',
  },
  algorithms: {
    courseId: 'algorithms',
    name: 'Algorithms',
    primaryColor: '#10B981',
    secondaryColor: '#6EE7B7',
    accentColor: '#059669',
    bgTint: '#ECFDF5',
    icon: 'graph-outline',
    badge: 'Patterns & Visual Lab',
    visualMotif: 'graph_tree',
    tagline: '10 Master Levels: Sliding Window, DP, Network Flow, and Dry-run debugging.',
  },
};

export function getCourseIdentity(courseId: string): CourseVisualIdentity {
  const norm = courseId.toLowerCase().replace(/-/g, '_');
  return (
    COURSE_IDENTITIES[norm] || {
      courseId,
      name: courseId.charAt(0).toUpperCase() + courseId.slice(1),
      primaryColor: '#E53935',
      secondaryColor: '#FFB300',
      accentColor: '#0288D1',
      bgTint: '#FEF2F2',
      icon: 'compass-outline',
      badge: 'Course Journey',
      visualMotif: 'default',
      tagline: 'Master foundational engineering skills step by step.',
    }
  );
}
